-- fix_synonyms_and_grants.sql
-- Chạy bằng SYS (AS SYSDBA) trong PDB (ví dụ XEPDB1)
-- Mục đích: tạo private synonyms cho các user ứng dụng và cấp quyền SELECT cần thiết

SET ECHO ON;

-- Danh sách user cần tạo synonym/grant
-- DPV001, DPV002, BS001..BS003, KTV001..KTV002, BN001..BN005

BEGIN
  NULL; -- chỉ để tránh lỗi khi chạy như script trong SQL Developer
END;
/
-- Tạo private synonyms: user."OBJECT" FOR SYS."OBJECT"
BEGINkho
  EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM DPV001."NHÂNVIÊN" FOR SYS."NHÂNVIÊN"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM DPV001."BỆNHNHÂN" FOR SYS."BỆNHNHÂN"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM DPV001."HSBA" FOR SYS."HSBA"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM DPV001."HSBA_DV" FOR SYS."HSBA_DV"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM DPV001."ĐƠNTHUỐC" FOR SYS."ĐƠNTHUỐC"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM DPV001."THÔNGBÁO" FOR SYS."THÔNGBÁO"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
-- Lặp cho BS001..BS003
BEGIN EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM BS001."NHÂNVIÊN" FOR SYS."NHÂNVIÊN"'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM BS001."BỆNHNHÂN" FOR SYS."BỆNHNHÂN"'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM BS001."HSBA" FOR SYS."HSBA"'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM BS001.VW_HSBA_DV_KTV FOR SYS.VW_HSBA_DV_KTV'; EXCEPTION WHEN OTHERS THEN NULL; END;/

BEGIN EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM BS002."NHÂNVIÊN" FOR SYS."NHÂNVIÊN"'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM BS002."BỆNHNHÂN" FOR SYS."BỆNHNHÂN"'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM BS002."HSBA" FOR SYS."HSBA"'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM BS002.VW_HSBA_DV_KTV FOR SYS.VW_HSBA_DV_KTV'; EXCEPTION WHEN OTHERS THEN NULL; END;/

BEGIN EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM BS003."NHÂNVIÊN" FOR SYS."NHÂNVIÊN"'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM BS003."BỆNHNHÂN" FOR SYS."BỆNHNHÂN"'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM BS003."HSBA" FOR SYS."HSBA"'; EXCEPTION WHEN OTHERS THEN NULL; END;/

-- KTV
BEGIN EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM KTV001."NHÂNVIÊN" FOR SYS."NHÂNVIÊN"'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM KTV001."HSBA_DV" FOR SYS."HSBA_DV"'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM KTV002."NHÂNVIÊN" FOR SYS."NHÂNVIÊN"'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM KTV002."HSBA_DV" FOR SYS."HSBA_DV"'; EXCEPTION WHEN OTHERS THEN NULL; END;/

-- BN patients
BEGIN EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM BN001."BỆNHNHÂN" FOR SYS."BỆNHNHÂN"'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM BN001."HSBA" FOR SYS."HSBA"'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM BN002."BỆNHNHÂN" FOR SYS."BỆNHNHÂN"'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM BN003."BỆNHNHÂN" FOR SYS."BỆNHNHÂN"'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM BN004."BỆNHNHÂN" FOR SYS."BỆNHNHÂN"'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM BN005."BỆNHNHÂN" FOR SYS."BỆNHNHÂN"'; EXCEPTION WHEN OTHERS THEN NULL; END;/

-- Grant SELECT cho các user (nếu cần)
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON SYS."NHÂNVIÊN" TO BS001'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON SYS."BỆNHNHÂN" TO BS001'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON SYS."NHÂNVIÊN" TO BN001'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON SYS."BỆNHNHÂN" TO BN001'; EXCEPTION WHEN OTHERS THEN NULL; END;/

-- Lặp grant cho các user khác (DPV, KTV, BS002..)
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON SYS."NHÂNVIÊN" TO BS002'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON SYS."BỆNHNHÂN" TO BS002'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON SYS."NHÂNVIÊN" TO BS003'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON SYS."BỆNHNHÂN" TO BS003'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON SYS."HSBA" TO BS001'; EXCEPTION WHEN OTHERS THEN NULL; END;/

BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON SYS."HSBA_DV" TO KTV001'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'GRANT SELECT ON SYS."HSBA_DV" TO KTV002'; EXCEPTION WHEN OTHERS THEN NULL; END;/

COMMIT;

PROMPT --- fix_synonyms_and_grants.sql completed ---

-- HƯỚNG DẪN: chạy bằng SYS trong PDB
-- sqlplus sys/YourSysPwd@//HOST:1521/XEPDB1 AS SYSDBA
-- SQL> @D:\full\path\to\database\fix_synonyms_and_grants.sql
