-- =====================================================================
-- File: 00_RESET_ATBM.sql
-- Purpose: Reset all project-owned Oracle objects/users/roles so the
--          database can be installed again from 01_schema.sql.
-- Run as: SYSTEM or SYSDBA.
-- Notes:
--   - Close HospitalSystem.exe and SQL Developer sessions using demo users.
--   - This script only targets ATBM project objects/users/roles.
-- =====================================================================

SET DEFINE OFF;
SET ECHO ON;
SET SERVEROUTPUT ON;

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

PROMPT === RESET ATBM PROJECT START ===

-- ---------------------------------------------------------------------
-- 1. Kill active demo-user sessions, otherwise DROP USER may fail.
-- ---------------------------------------------------------------------
BEGIN
  FOR s IN (
    SELECT sid, serial#
    FROM v$session
    WHERE username IN (
      'DPV001','DPV002',
      'BS001','BS002','BS003',
      'KTV001','KTV002',
      'BN001','BN002','BN003','BN004','BN005',
      'NV01','NV02','TP01','GD01',
      'TEST_ATBM_USER'
    )
  ) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || s.sid || ',' || s.serial# || ''' IMMEDIATE';
    EXCEPTION
      WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skip killing session ' || s.sid || ',' || s.serial# || ': ' || SQLERRM);
    END;
  END LOOP;
END;
/

-- ---------------------------------------------------------------------
-- 2. Remove VPD/FGA/Unified Audit/OLS policies if they exist.
-- ---------------------------------------------------------------------
BEGIN DBMS_RLS.DROP_POLICY('SYSTEM', 'HSBA',      'POL_BACSI_HSBA');      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_RLS.DROP_POLICY('SYSTEM', 'BỆNHNHÂN',  'POL_BACSI_BENHNHAN');  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_RLS.DROP_POLICY('SYSTEM', 'ĐƠNTHUỐC',  'POL_BACSI_DONTHUOC');  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_RLS.DROP_POLICY('SYSTEM', '"HSBA"',     'POL_BACSI_HSBA');      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_RLS.DROP_POLICY('SYSTEM', '"BỆNHNHÂN"', 'POL_BACSI_BENHNHAN');  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_RLS.DROP_POLICY('SYSTEM', '"ĐƠNTHUỐC"', 'POL_BACSI_DONTHUOC');  EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN DBMS_FGA.DROP_POLICY('SYSTEM', 'ĐƠNTHUỐC', 'AUD_FGA_DONTHUOC_UPDATE'); EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_FGA.DROP_POLICY('SYSTEM', 'HSBA', 'AUD_FGA_HSBA_BACSI_UPDATE_SUCCESS'); EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_FGA.DROP_POLICY('SYSTEM', 'HSBA', 'AUD_FGA_HSBA_BACSI_UPDATE'); EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_FGA.DROP_POLICY('SYSTEM', 'HSBA', 'AUD_FGA_HSBA_ILLEGAL_UPDATE'); EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_FGA.DROP_POLICY('SYSTEM', 'HSBA_DV', 'AUD_FGA_HSBADV_ILLEGAL'); EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'NOAUDIT POLICY AUD_UA_HSBA_ILLEGAL_UPDATE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP AUDIT POLICY AUD_UA_HSBA_ILLEGAL_UPDATE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'NOAUDIT POLICY AUD_UA_HSBADV_ILLEGAL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP AUDIT POLICY AUD_UA_HSBADV_ILLEGAL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    BEGIN
      SA_POLICY_ADMIN.REMOVE_TABLE_POLICY(
        policy_name => 'HOSPITAL_POLICY',
        schema_name => 'SYSTEM',
        table_name => 'THÔNGBÁO'
      );
    END;]';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    BEGIN
      SA_SYSDBA.DROP_POLICY(
        policy_name => 'HOSPITAL_POLICY',
        drop_column => TRUE
      );
    END;]';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ---------------------------------------------------------------------
-- 3. Stop scheduler jobs/procedures/directories created by backup script.
-- ---------------------------------------------------------------------
BEGIN DBMS_SCHEDULER.DROP_JOB('JOB_DAILY_BACKUP', force => TRUE); EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_SCHEDULER.DROP_JOB('JOB_WEEKLY_BACKUP', force => TRUE); EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE SP_AUTO_BACKUP'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP DIRECTORY BACKUP_DIR'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ---------------------------------------------------------------------
-- 4. Drop triggers, views, packages, functions and project tables.
-- ---------------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_AUDIT_DONTHUOC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_AUDIT_HSBA_DV'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_AUDIT_HSBA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_DONTHUOC_BENHNHAN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_HSBA_BENHNHAN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_BENHNHAN_SELF'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_HSBA_DV_KTV'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE VPD_DIEUPHOI_PKG'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE VPD_BACSI_PKG'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE AUDIT_LOG CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FLASHBACK_DEMO_LOG CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE "THÔNGBÁO" CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE "ĐƠNTHUỐC" CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE "HSBA_DV" CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE "HSBA" CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE "NHÂNVIÊN" CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE "BỆNHNHÂN" CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP TABLE NHANVIEN_DATA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DUAN_DATA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FN_NEXT_MABN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FN_NEXT_MANV'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FN_NEXT_MAHSBA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_BENHNHAN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_NHANVIEN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HSBA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/


-- Drop column-level SELECT helper views created by PH1 admin UI.
BEGIN
  FOR v IN (SELECT view_name FROM user_views WHERE view_name LIKE 'VW_COL_%') LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP VIEW "' || v.view_name || '"';
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
  END LOOP;
END;
/

-- ---------------------------------------------------------------------
-- 5. Drop roles and users.
-- ---------------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP ROLE ROLE_DIEUPHOI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE ROLE_BACSI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE ROLE_KTHUATVIEN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE ROLE_BENHNHAN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE ROLE_NHANVIEN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE ROLE_QUANLY'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE ROLE_GIAMDOC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE TEST_ATBM_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  FOR u IN (
    SELECT username
    FROM dba_users
    WHERE username IN (
      'DPV001','DPV002',
      'BS001','BS002','BS003',
      'KTV001','KTV002',
      'BN001','BN002','BN003','BN004','BN005',
      'NV01','NV02','TP01','GD01',
      'TEST_ATBM_USER'
    )
  ) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP USER "' || u.username || '" CASCADE';
      DBMS_OUTPUT.PUT_LINE('Dropped user ' || u.username);
    EXCEPTION
      WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Could not drop user ' || u.username || ': ' || SQLERRM);
    END;
  END LOOP;
END;
/

PURGE RECYCLEBIN;

-- Reset must not leave this hidden flag enabled, otherwise objects created
-- by following scripts in XEPDB1 become ORACLE_MAINTAINED and hard to drop.
ALTER SESSION SET "_ORACLE_SCRIPT"=false;

PROMPT === RESET ATBM PROJECT DONE ===
PROMPT Now run: @01_schema.sql, @02_data.sql, @03_accounts.sql, @04_rbac.sql, @05_vpd.sql
